theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
# bufferline = "never"
# cursorline = true
line-number = "relative"
# auto-completion = true
auto-save=true
rulers = [120]
true-color = true
mouse = true
scrolloff = 10
shell = ["zsh", "-c"]
color-modes = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-pairs = true
idle-timeout = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.soft-wrap]
enable=true


[editor.file-picker]
hidden = false
parents = false
git-ignore = false

# [editor.whitespace]
# render = "all"
# or control each character
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# tab = "→"
# newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
# auto-signature-help = true
# display-signature-help-docs = true
display-messages = true
display-inlay-hints = true

[keys.normal]
# C-s = ":w"
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
G = "goto_file_end"

V = ["select_mode", "extend_to_line_bounds"]
x = "delete_selection"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection"]
o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]
# Uncanny valley stuff, this makes w and b behave as they do Vim
w = ["move_next_word_start", "move_char_right", "collapse_selection"]
e = ["move_next_word_end", "collapse_selection"]
b = ["move_prev_word_start", "collapse_selection"]
"tab" = ":bn"
"S-tab" = ":bp"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds","yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal.space]
q = ":q"
Q = ":qa!"
x = ":buffer-close"
X = ":buffer-close-others"
n = ":new"

[keys.normal.space.c]
w = ":write"
r = [":w", ":config-reload"]
o = ":config-open"
s = ":o ~/.config/helix/languages.toml" 
l = ":log-open"
  
[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
k = { j = "normal_mode" }
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
G = "goto_file_end"
# x = "delete_selection"
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]
p = "replace_selections_with_clipboard" # No life without this
P = "paste_clipboard_before"
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
